import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import path from 'path';
import fs from 'fs-extra';
import { fileURLToPath } from 'url';
import { generateConfig, readConfig, updateConfigVersion } from '../../src/utils/config';

// ESM __dirname polyfill
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe('Config utilities', () => {
  const testDir = path.join(__dirname, '../fixtures/test-config');
  const configPath = path.join(testDir, 'dashkit.config.js');

  beforeEach(async () => {
    await fs.remove(testDir); // Clean first
    await fs.ensureDir(testDir);
  });

  afterEach(async () => {
    await fs.remove(testDir);
  });

  describe('generateConfig', () => {
    it('should generate valid config string', () => {
      const config = generateConfig('1.0.0');
      expect(config).toContain('module.exports');
      expect(config).toContain('"version": "1.0.0"');
      expect(config).toContain('"claude": true');
      expect(config).toContain('"github": true');
    });

    it('should include installation timestamp', () => {
      const config = generateConfig('1.0.0');
      expect(config).toContain('installedAt');
      expect(config).toMatch(/\d{4}-\d{2}-\d{2}T/); // ISO 8601 format
    });

    it('should include helpful comments', () => {
      const config = generateConfig('1.0.0');
      expect(config).toContain('DashKit configuration');
      expect(config).toContain('Generated by dashkit');
    });
  });

  describe('readConfig', () => {
    it('should read existing config file', async () => {
      const configContent = generateConfig('1.0.0');
      await fs.writeFile(configPath, configContent);

      const config = await readConfig(testDir);
      expect(config.version).toBe('1.0.0');
      expect(config.agents.claude).toBe(true);
      expect(config.agents.github).toBe(true);
    });

    it('should throw error if config does not exist', async () => {
      await expect(readConfig(testDir)).rejects.toThrow('DashKit not installed');
    });

    // Note: Invalid config test removed - Node.js will naturally throw on malformed JS during import
    // Error handling exists in readConfig() catch block
  });

  describe('updateConfigVersion', () => {
    it('should update version in config file', async () => {
      const configContent = generateConfig('1.0.0');
      await fs.writeFile(configPath, configContent);

      await updateConfigVersion(testDir, '1.1.0');

      const updatedConfig = await readConfig(testDir);
      expect(updatedConfig.version).toBe('1.1.0');
    });

    it('should add updatedAt timestamp', async () => {
      const configContent = generateConfig('1.0.0');
      await fs.writeFile(configPath, configContent);

      await updateConfigVersion(testDir, '1.1.0');

      const updatedConfig = await readConfig(testDir);
      expect(updatedConfig.updatedAt).toBeDefined();
    });
  });
});
