import path from 'path';
import fs from 'fs-extra';
import { fileURLToPath } from 'url';

export interface DashKitConfig {
  version: string;
  installedAt: string;
  updatedAt?: string;
  agents: {
    claude: boolean;
    github: boolean;
  };
}

export function generateConfig(version: string): string {
  const config: DashKitConfig = {
    version,
    installedAt: new Date().toISOString(),
    agents: {
      claude: true,
      github: true,
    },
  };

  return `// DashKit configuration
// Generated by dashkit v${version}
// Documentation: https://github.com/sfwd-dashapps/dashkit

module.exports = ${JSON.stringify(config, null, 2)};
`;
}

export async function readConfig(targetDir: string): Promise<DashKitConfig> {
  const configPath = path.join(targetDir, 'dashkit.config.js');

  if (!(await fs.pathExists(configPath))) {
    throw new Error('DashKit not installed. Run: dashkit init --here');
  }

  try {
    // Use dynamic import for ES modules with cache-busting for test reliability
    // In production, config doesn't change between reads, so caching is fine
    // In tests, we may overwrite config files, so we need fresh imports
    const configUrl = `file://${configPath}?t=${Date.now()}`;
    const configModule = await import(configUrl);
    return configModule.default || configModule;
  } catch (error) {
    throw new Error('Invalid dashkit.config.js. Delete and reinstall with: dashkit init --force');
  }
}

export async function updateConfigVersion(
  targetDir: string,
  newVersion: string
): Promise<void> {
  const configPath = path.join(targetDir, 'dashkit.config.js');
  const config = await readConfig(targetDir);

  config.version = newVersion;
  config.updatedAt = new Date().toISOString();

  const configContent = generateConfig(newVersion);
  await fs.writeFile(configPath, configContent);
}

export async function writeConfig(
  targetDir: string,
  version: string
): Promise<void> {
  const configPath = path.join(targetDir, 'dashkit.config.js');
  const configContent = generateConfig(version);
  await fs.writeFile(configPath, configContent);
}
